/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.sxmp;
public final class Version {
    private static final String TIMESTAMP="20130206-1151";
    private static final String VERSION="1.4.2";
    private static final String NAME="ch-sxmp";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="1.4.2 (Build @ 20130206-1151)";
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20130206-1151" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-sxmp" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "1.4.2" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "1.4.2 (Build @ 20130206-1151)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
