/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.sxmp;
public final class Version {
    private static final String COMMIT="b3469c5c";
    private static final String TIMESTAMP="20130325-1708";
    private static final String VERSION="1.4.2-SNAPSHOT";
    private static final String NAME="ch-sxmp";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="1.4.2-SNAPSHOT (commit b3469c5c @ 20130325-1708)";
    /** Returns the library source control commit tag such as "b3469c5c" */
    static public String getCommit() { return COMMIT; }
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20130325-1708" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-sxmp" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "1.4.2-SNAPSHOT" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "1.4.2-SNAPSHOT (commit b3469c5c; ts 20130325-1708)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
