/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.commons.util;
public final class Version {
    private static final String TIMESTAMP="20110818-1113";
    private static final String VERSION="5.1.1";
    private static final String NAME="ch-commons-util";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="5.1.1 (Build @ 20110818-1113)";
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20110818-1113" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-commons-util" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "5.1.1" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "5.1.1 (Build @ 20110818-1113)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
