/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.commons.xbean;
public final class Version {
    private static final String TIMESTAMP="20120215-2012";
    private static final String VERSION="2.0.0-SNAPSHOT";
    private static final String NAME="ch-commons-xbean";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="2.0.0-SNAPSHOT (Build @ 20120215-2012)";
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20120215-2012" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-commons-xbean" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "2.0.0-SNAPSHOT" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "2.0.0-SNAPSHOT (Build @ 20120215-2012)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
