/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.commons.rfs;
public final class Version {
    private static final String TIMESTAMP="20110918-1906";
    private static final String VERSION="1.2.0";
    private static final String NAME="ch-commons-rfs";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="1.2.0 (Build @ 20110918-1906)";
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20110918-1906" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-commons-rfs" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "1.2.0" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "1.2.0 (Build @ 20110918-1906)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
