/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.commons.sql;
public final class Version {
    private static final String TIMESTAMP="20111019-0018";
    private static final String VERSION="1.1.0";
    private static final String NAME="ch-commons-sql";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="1.1.0 (Build @ 20111019-0018)";
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20111019-0018" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-commons-sql" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "1.1.0" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "1.1.0 (Build @ 20111019-0018)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
