/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.commons.charset;
public final class Version {
    private static final String TIMESTAMP="20110818-1442";
    private static final String VERSION="2.2.1";
    private static final String NAME="ch-commons-charset";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="2.2.1 (Build @ 20110818-1442)";
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20110818-1442" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-commons-charset" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "2.2.1" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "2.2.1 (Build @ 20110818-1442)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
